name: Get YouTube Live Video M3U8 and Frame
on:
  push:
    branches:
      - main
jobs:
  get_video:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install youtube-dl
      run: |
        pip3 install you-get
    - name: Get YouTube Live Video M3U8
      run: |
        you-get https://www.youtube.com/watch?v=qItL005LUik
  
