name: Get YouTube Live Video M3U8 and Frame
on:
  push:
    branches:
      - main
jobs:
  get_video:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run
      run: |
        ./main.py
  
