name: Get YouTube Live Video M3U8 and Frame
on:
  push:
    branches:
      - main
jobs:
  get_video:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: get html
      run: |
        curl https://www.youtube.com/watch?v=RCp9hnp7r6Q
  
