name: Upload Frame to Github
on:
  push:
    branches:
      - master
jobs:
  upload_frame:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install m3u8
    - name: Extract Frame
      run: |
        m3u8_url="<m3u8_url>"
        m3u8 = m3u8.load(m3u8_url)
        first_segment = m3u8.segments[0]
        first_segment.download()
        first_segment.convert_to_jpg()
    - name: Upload Frame
      uses: actions/upload-artifact@v2
      with:
        name: frame
        path: frame.jpg
