name: Get YouTube Live Video M3U8 and Frame
on:
  push:
    branches:
      - main
jobs:
  get_video:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Running
      run: |
        ./main.py
  
